services:
  bot-layla:
    build: .
    image: layla-bot:1.0
    container_name: layla-bot
    restart: unless-stopped
    volumes:
      - /home/santiago/services/infra/web/nginx/html/layla-bot:/app/layla-media
    env_file:
      - .env

